### PR TITLE
Support multi workers

### PR DESCRIPTION
**Pull request by okkez**
See also: http://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released

### CODE REVIEW

**Comment by okkez** [comment]
ping @shunwen

**Comment by shunwen** [comment]
@okkez hi, I will merge this this week, thanks. I don't know which config I missed that I don't get email notification for PR... thanks for pinging.

**Comment by shunwen** [comment]
@okkez Done. Sorry for the late response.

**Comment by okkez** [comment]
No problem. Thank you for your work!

**Pull request merged**
