### PR TITLE
Migrate to Fluentd v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
TODOs to release new version for Fluentd v0.14:

* Release new version for Fluentd v0.12.x
* Add "Requirements" section same as [fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3)

See also: http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

**Comment by shunwen** [comment]
@okkez Thanks. I will release the new version this week.

**Comment by okkez** [comment]
Thanks!

**Comment by shunwen** [comment]
@okkez sorry for being late, I updated the plugin to 0.4.0 yesterday. Let me know if anything goes wrong. Thanks!

**Pull request merged**
